version: "3"
services:
  mongodb: 
    image: hackerregister.azurecr.io/mongo

  mongo-seed: #this is used to populate the DB, see dockerfile for import command
    build: 
      context: ./db-seed
      args:
        HOST: mongodb
    image: hackerregister.azurecr.io/tumo_db-seed
    depends_on:
      - mongodb
          
  api:
    build:
      context: ./api
    image: hackerregister.azurecr.io/tumo_api
    depends_on:
      - mongodb
    environment:
      PORT: 4000
      # MONGO_URI: ${MONGO_URI}
      MONGO_URI: mongodb://mongodb:27017/dobook

  frontend:
    build:
      context: ./frontend
    image: hackerregister.azurecr.io/tumo_frontend
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 4000
    ports:
      - "80:80"
